### ISSUE TITLE
Preparar ambiente frontend

### ISSUE THREAD

**Issue by huogerac** [confraria-devpro/hackernews-clone#5]
Vamos precisar do NodeJS instalado para iniciar com o projeto do Frontend.
É muito fácil você ter que lidar com mais de um projeto (frontend), logo **ter o controle de qual versão do Node** é muito importante.

A boa notícia é que pelo menos isto no mundo Javascript é tranquilo. Precisamos disto:

- Instalar **Node 14 (LTS)** utilizando Node Version Manager (**NVM**)
- Verifique que tem o node instalado usando `node -v`
- Verifique que tem o NPM instalado usando `npm -v`

Eu utilizo o script abaixo sempre que formato minha maquina, tem um link para um post também:
- https://github.com/huogerac/dev-tools/blob/master/elementaryos5/03_install_node.sh
- https://heynode.com/tutorial/install-nodejs-locally-nvm/

## Dúvida:
- Alguem tem um link legal para instalar no windows?

DICA: Não instale node usando `apt-get install nodejs`

**Comment by serlus** [comment]
Opa legal, já tenho nvm instalado (não tenho ideia se da forma correta), mas ta setado com default o 16 por conta de um projeto da empresa. Mas a ideia é essa certo?

```
┌─(~)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(serlus@serlus-ThinkPad-T450:pts/2)─┐
└─(09:30:55)──> nvm ls                                                                                                                                                         ──(qui,set30)─┘
       v14.17.5
        v15.2.1
->      v16.3.0
         system
default -> node (-> v16.3.0)
iojs -> N/A (default)
unstable -> N/A (default)
node -> stable (-> v16.3.0) (default)
stable -> 16.3 (-> v16.3.0) (default)
lts/* -> lts/fermium (-> v14.17.5)
lts/argon -> v4.9.1 (-> N/A)
lts/boron -> v6.17.1 (-> N/A)
lts/carbon -> v8.17.0 (-> N/A)
lts/dubnium -> v10.24.1 (-> N/A)
lts/erbium -> v12.22.5 (-> N/A)
lts/fermium -> v14.17.5
┌─(~)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(serlus@serlus-ThinkPad-T450:pts/2)─┐
└─(09:31:54)──> npm -v                                                                                                                                                         ──(qui,set30)─┘
7.15.1
┌─(~)────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────(serlus@serlus-ThinkPad-T450:pts/2)─┐
└─(09:32:46)──> node -v                                                                                                                                                        ──(qui,set30)─┘
v16.3.0

```

**Comment by tiagotardelli** [comment]
Feito
![image](https://user-images.githubusercontent.com/694103/135474559-c6a06703-87ea-4ddc-ac06-ada5c9cfd0cd.png)

**Comment by alvesgabriel** [comment]
Eu uso o [asdf](https://github.com/asdf-vm/asdf) para gerenciar múltiplas versões de várias linguagens com apenas um CLI. Dá para usá-lo para Python e Nodejs.

**Comment by huogerac** [comment]
Que massa @alvesgabriel ! vou dar uma olhada neste asdf (pensei que era zueira)
Gostei e obrigado pela informação!
